version: "3.4"

services:
  db:
    image: postgres
    volumes:
      - d:/Temp/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: freezr
    ports:
      - 5432:5432

  message-queue:
    image: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222

  prometheus:
    image: huserben/freezr.prometheus
    build:
      context: ../Prometheus
      dockerfile: Dockerfile

    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

  freezr-frontend:
    image: huserben/freezr.frontend
    build:
      context: ../freezr.frontend
      dockerfile: Dockerfile_prod

    ports:
      - "1337:80"

  freezr-databaseservice:
    image: huserben/freezr.databaseservice
    build:
      context: ../Freezr.Backend/
      dockerfile: Services/Freezr.Services.Database/Dockerfile

    depends_on:
      - "message-queue"

    environment:
      MESSAGE_QUEUE_URL: nats://message-queue:4222
      PostgresDocker: "Server=db;Port=5432;Database=freezr;User Id=postgres;Password=mysecretpassword;"

  freezr-backend:
    image: huserben/freezr.backend
    build:
      context: ../Freezr.Backend/
      dockerfile: Freezr.Backend/Dockerfile

    environment:
      MESSAGE_QUEUE_URL: nats://message-queue:4222

    ports:
      - 32777:80
      - 32778:443

    depends_on:
      - "db"
      - "message-queue"
