apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgresvolume
  name: postgresvolume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
