apiVersion: v1
kind: Service
metadata:
  name: message-queue
spec:
  selector:
    app: message-queue

  ports:
  - name: "4222"
    port: 4222
    targetPort: 4222
  - name: "6222"
    port: 6222
    targetPort: 6222
  - name: "8222"
    port: 8222
    targetPort: 8222
