version: "3.4"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - d:/Temp/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: freezr
    ports:
      - 5432:5432

  message-queue:
    image: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222

  freezr.frontend:
    build:
      context: ../freezr.frontend
      dockerfile: Dockerfile_prod

    ports:
      - "1337:80"

  freezr.databaseservice:
    build:
      context: .
      dockerfile: Services/Freezr.Services.Database/Dockerfile

    depends_on:
      - "message-queue"

    environment:
      MESSAGE_QUEUE_URL: nats://message-queue:4222
      PostgresDocker: "Server=db;Port=5432;Database=freezr;User Id=postgres;Password=mysecretpassword;"

  freezr.backend:
    build:
      context: .
      dockerfile: Freezr.Backend/Dockerfile

    environment:
      MESSAGE_QUEUE_URL: nats://message-queue:4222

    ports:
      - 32777:80
      - 32778:443

    depends_on:
      - "db"
      - "message-queue"
