version: '3.4'

services:
  freezr.backend:
    container_name: freezr.backend
    image: ${DOCKER_REGISTRY-}freezrbackend
    build:
      context: .
      dockerfile: Freezr.Backend/Dockerfile

    ports:
      - 32777:80
      - 32778:443

    depends_on:
      - "db"

  freezr.frontend:
    container_name: freezr.frontend
    build:
      context: ../freezr.frontend
      dockerfile: Dockerfile_prod
    
    ports:
      - '1337:80'

  db:
    container_name: freezr.database
    image: postgres
    restart: always
    volumes:
      - d:/Temp/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: freezr
    ports:
        - 5432:5432